### ISSUE TITLE
Branch-less macros?

### ISSUE THREAD

**Issue by textbrowser** [maandree/libzahl#3]
You may be able (probably unlikely) to sip a little more performance if you replace the logical operator in the following (from libzahl/zahl/inlines.h) with a bitwise operator. If you decide to change zzero(), there are other candidates in inlines.h worth reviewing.

`
ZAHL_INLINE int zzero(z_t a) { return !a->sign; }
`

`... {return a->sign & 0;}
`
But, I haven't looked at the assembler code.

**Comment by maandree** [comment]
Or equivalently `{return 0;}`, which is even faster.

Jokes aside, this implementation is already optimal.

**Comment by textbrowser** [comment]
Apologies.

```^ 0```

```
#include <stdio.h>

int main(int argc, char *argv[])
{
  int a = argc % 2;

  printf("%d\n", a ^ 0);
  return 0;
}
```
```
#include <stdio.h>

int main(int argc, char *argv[])
{
  int a = argc % 2;

  printf("%d\n", !a);
  return 0;
}
```
```
diff bitwise.s logical.s 
18c18
< 	movl	$.LC0, %esi
---
> 	xorl	%edx, %edx
20c20,23
< 	leal	(%rdi,%rax), %edx
---
> 	movl	$.LC0, %esi
> 	addl	%eax, %edi
> 	andl	$1, %edi
> 	cmpl	%eax, %edi
22,23c25
< 	andl	$1, %edx
< 	subl	%eax, %edx
---
> 	sete	%dl
```
And...
```
#include <limits.h>
#include <stdio.h>

int main(void)
{
  char r = 0;
  int a = 0;

  for(int i = 1; i < INT_MAX; i++)
    {
      r = i % 2;
      a += !r;
    }

  printf("%d\n", a);
  return a;
}
```
```
time ./a.out 
1073741823

real	0m2.083s
user	0m2.080s
sys	0m0.000s
```
**versus**
```
time ./a.out 
1073741823

real	0m0.525s
user	0m0.524s
sys	0m0.000s
```
(r ^ 0)
Both compiled with -O3.

**Comment by textbrowser** [comment]
And can you shrink the **sign** variable into a character or does it have to be an integer?

**Comment by maandree** [comment]
`^ 0` too doesn't work, it doesn't change the value in any way. Note that `a->sign` has one of the values −1, 0, and +1. Additionally, in C, a 8-bit −1 can be stored as any of the following bit strings: 11111111, 11111110 and 10000001.

**Comment by maandree** [comment]
I'm not recall why I choose to use `int`, but I'm pretty sure I gave `signed char` a consideration.

**Comment by textbrowser** [comment]
Ah, I thought sign was either 0 or 1. Why can it be -1? Either you have a sign (1) or not (0).

**Comment by maandree** [comment]
The word “sign” isn't really that well designed. Both − and + are signs, and 0 is unsigned (but can be signed in some contexts). I cause to have a variable that tells be me what the signum function returns because its seemed like the simplest solution. If `sign` is 0 it does have any bits stored, I choose the name `sign` over `signum` because both − and + are signs (attributes) and signum is a function (not an attribute). If I change this it the future, I will call the variable `nonnegative`, `nonpositive`, `positive`, or `negative`.
